version: '3.7'

services:
  streamer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONSUMER_KEY
        - CONSUMER_SECRET
        - ACCESS_TOKEN
        - ACCESS_TOKEN_SECRET
        - MONGO_HOST=mongodb://root:example@mongo
    restart: always
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4.2.0-bionic
    restart: always
    command: --wiredTigerCacheSizeGB 1.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
